config/routes.rb
Rails.application.routes.draw do
  resources :media_items
  resources :media_items

  devise_for :users

  root to: "media_items#index"
end

app/models/add_to_media_collection.rb
class AddToMediaCollection

  attr_reader :user, :url, :visibility

  def initialize(options)
    @user = options.fetch(:user)
    @url = options.fetch(:url)
    @visibility = options.fetch(:public)
  end

  def execute!
    MediaRepository.add(user: user, url: url, public: visibility).tap do |item|
      if item.valid?
        ScrapeTitleJob.perform_later(item.id)
      end
    end
  end

end

app/models/change_item_visibility.rb
class ChangeItemVisibility

  attr_reader :media_item, :new_visibility

  def initialize(options)
    @media_item = options.fetch(:media_item)
    @new_visibility = options.fetch(:public)
  end

  def execute!
    media_item.public = new_visibility
    media_item.save!
  end

end

app/models/media_browse.rb
class MediaBrowse

  class NoUser; end

  attr_reader :user

  def initialize(options)
    @user = options.fetch(:user, NoUser) || NoUser
  end

  def items
    MediaRepository.visible_for(user)
  end
end

app/models/media_item.rb
class MediaItem < ActiveRecord::Base
  self.inheritance_column = nil

  belongs_to :user

  validates :url, presence: true

  auto_html_for :url do
    html_escape
    image
    youtube(width: 400, height: 250, autoplay: false)
    soundcloud
    instagram
    link :target => "_blank", :rel => "nofollow"
    simple_format
  end

end

app/models/media_repository.rb
class MediaRepository
  def self.add(options)
    MediaItem.create(options)
  end

  def self.where(*options)
    MediaItem.where(*options)
  end

  def self.visible_for(user)
    if user == MediaBrowse::NoUser || user.blank?
      MediaItem.where(public: true)
    else
      MediaItem.where(user: user) + MediaItem.where('user_id != ? AND public = ?', user.id, true)
    end
  end

  def self.find(*args)
    MediaItem.find(*args)
  end
end

app/models/media_search.rb
class MediaSearch
  attr_reader :user

  def initialize(options)
    @user = options.fetch(:user)
  end

  def items
    MediaRepository.visible_for(user)
  end
end

app/models/public_media_items.rb
class PublicMediaItems
  def public
    MediaRepository.where(public: true)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :media_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def show
  end
end

app/controllers/media_items_controller.rb
class MediaItemsController < ApplicationController
  before_filter :set_media_item, only: [:edit, :update]

  def index
    @media_items = MediaRepository.visible_for(current_user)
  end

  def new
    @media_item = MediaItem.new
  end

  def edit
  end

  def create
    @media_item = AddToMediaCollection.new(media_item_params.merge(user: current_user)).execute!
    if @media_item.valid?
      redirect_to media_items_path
    else
      render "new"
    end
  end

  def update
    if @media_item.user == current_user
      ChangeItemVisibility.new(media_item: @media_item, public: params[:media_item][:public]).execute!
    end
    redirect_to media_items_path
  end

  private
    def media_item_params
      params.require(:media_item).permit(:url, :public)
    end

    def set_media_item
      @media_item = MediaRepository.find(params[:id])
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_sidebar.html.erb
<ul class="side-nav">
  <li>
    <%= link_to "Homepage", media_items_path %>
  </li>
  <li>
    <%= link_to "Add new media item", new_media_item_path %>
  </li>

</ul>

app/views/application/_top_bar.html.erb
<div class="row">
  <div class="large-12 columns">
    <h1>Media Vault</h1>
  </div>
</div>
<div class="row">
  <div class="large-12 columns">
    <ul class="inline-list right">
      <% if user_signed_in? %>

        <li>
          <%= link_to "Homepage", media_items_path, class: 'tiny button' %>
        </li>
        <li>
          <%= link_to "Add new media item", new_media_item_path, class: 'tiny button' %>
        </li>
        <li>
          <%= link_to 'Logout', destroy_user_session_path, :method => :delete, class: 'tiny button' %>
        </li>
      <% else %>
        <li>
          <%= link_to 'Login', new_user_session_path, class: 'tiny button'  %>
        </li>
        <li>
          <%= link_to 'Register', new_user_registration_path, class: 'tiny button'  %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/index.html.erb
<h1>Items#index</h1>
<p>Find me in app/views/items/index.html.erb</p>

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/items/show.html.erb
<h1>Items#show</h1>
<p>Find me in app/views/items/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "HitfoxMedia" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <input id="current_user_id" type="hidden" value="<%= user_signed_in? ? current_user.id : nil %>" />

    <%= render "top_bar" %>

    <div class="row">
      <div class="large-9 push-3 columns">
        <%= yield %>
       </div>
      <div class="large-3 pull-9 columns">
        <%= render "sidebar" %>
      </div>
     </div>
  </body>
</html>

app/views/media_items/_form.html.erb
<%= form_for(@media_item) do |f| %>
  <% if @media_item.errors.any? %>
    <div id="error_explanation">
     <h2>Invalid Item</h2>
     <ul>
      <% @media_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :public %>
    <%= f.check_box :public %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/media_items/edit.html.erb
<%= render "form" %>

app/views/media_items/index.html.erb
<p id="notice"><%= notice %></p>

<%= react_component "SearchMediaItems", media_items: @media_items %>

app/views/media_items/new.html.erb
<%= render 'form' %>